# Generated by Django 5.1.7 on 2025-03-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelrequest',
            old_name='destination',
            new_name='end_location',
        ),
        migrations.RemoveField(
            model_name='travelrequest',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='travelrequest',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='travelrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='travelrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='project',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='purpose',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='start_location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='ticket_booking_mode',
            field=models.CharField(choices=[('Self', 'Self'), ('Travel Desk', 'Travel Desk')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='travel_mode',
            field=models.CharField(choices=[('Flight', 'Flight'), ('Train', 'Train'), ('Car', 'Car')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
