# Generated by Django 5.1.7 on 2025-03-12 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_travelrequest_user_alter_travelrequest_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelrequests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='travelrequest',
            table='travel_travelrequest',
        ),
    ]
