# Generated by Django 5.1.7 on 2025-03-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_remove_travelrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
