# Generated by Django 5.1.7 on 2025-03-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_travelrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrequest',
            name='status',
        ),
    ]
