# Generated by Django 5.1.7 on 2025-03-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_travelrequest_user_alter_travelrequest_end_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrequest',
            name='user',
        ),
    ]
