# Generated by Django 5.1.7 on 2025-03-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_travelrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrequest',
            name='user',
        ),
    ]
