# Generated by Django 5.1.7 on 2025-03-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_remove_travelrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
