# Generated by Django 5.1.7 on 2025-03-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_travelrequest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrequest',
            name='name',
        ),
    ]
