# Generated by Django 5.1.7 on 2025-03-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_remove_travelrequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='username',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
