# Generated by Django 5.1.7 on 2025-03-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_alter_travelrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
