# Generated by Django 5.1.7 on 2025-03-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_travelrequest_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='username',
            field=models.CharField(default='unknown_user', max_length=150),
        ),
    ]
