# Generated by Django 5.1.7 on 2025-03-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_alter_travelrequest_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='ticket_booking_mode',
            field=models.CharField(choices=[('Self', 'Self'), ('Travel Desk', 'Travel Desk')], max_length=100),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='travel_mode',
            field=models.CharField(choices=[('Flight', 'Flight'), ('Train', 'Train'), ('Car', 'Car')], max_length=100),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
